### ISSUE TITLE
특정 customer id에서만 403 에러 발생

### ISSUE THREAD

**Issue by C-Jaewon** [naver/searchad-apidoc#1013]
https://api.naver.com/billing/bizmoney api 요청시 10개중에 하나의 customer id에서 403에러가 발생하고 있어요. 왜 그런걸까요?

```python
# 에러 소스 코드
except requests.exceptions.RequestException as e:
    # HTTP 요청 관련 예외 처리 (ConnectionError, Timeout, HTTPError 등 포함)
    print(f"Request failed: {e}")
    print(f"Http status: {r.status_code}" if r else "No response received")
    print("Full traceback:")
```
```
Request failed: 403 Client Error: Forbidden for url: https://api.searchad.naver.com/billing/bizmoney
No response received
Full traceback:
Traceback (most recent call last):
  File "/home/amuz_chae/jwchae/python_nevada/nevada/Common/Connector.py", line 141, in get
    r.raise_for_status()  # HTTP 오류 발생 시 예외 발생
  File "/home/amuz_chae/env/napi/lib/python3.10/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
```

**Comment by searchad-api-customer-service** [comment]
@C-Jaewon 안녕하세요. 검색광고 API 담당자 입니다.

정확한 요청 정보를 알수 없어서 정확히 확인이 어렵지만 

1. 요청시 사용하는 API-KEY 및 xCustomerId 값이 정확한지 확인 부탁드립니다.
2. 그리고 광고주센터에서 권한 부여가 잘 되어있는지도 한번 확인 부탁드리겠습니다.

정확한 오류 확인을 위해서는 오류 응답 헤더에 포함된  transactionId 값을 코멘트로 추가해주시면 더  정확한 확인이 가능핧것 같습니다.

감사합니다.

**Comment by C-Jaewon** [comment]
권한 문제였네요 감사합니다.

**Comment by jaemitsu** [comment]
동일 문제가 발생하였는데, 권한문제 어떻게 설정하였는지 여쭤보고 싶습니다.
