### ISSUE TITLE
Ad : List 요청 방법 문의

### ISSUE THREAD

**Issue by dnt-walker** [naver/searchad-apidoc#346]
안녕하십니까!
문서에는  Ad 조회 요청에 Ad: list 가 있어서 사용할려고 하는데 동작을 하지않습니다.

아래와 같이 요청을 하면 권한 오류가 발생합니다.   
`GET /ncc/ads?ids=grp-a001-01-000000009585414%2Cgrp-a001-01-000000009585415 HTTP/1.1`

```
{"code":1018,"status":404,"title":"No permission to access the resource."}
java.lang.Exception: 404 Not Found. X-Transaction-ID: BG1TPSQN1DHSM, Response Body: {"code":1018,"status":404,"title":"No permission to access the resource."}
	at com.naver.searchad.api.util.RestClient.asObject(RestClient.java:143)
	at com.naver.searchad.api.rest.Ads.list(Ads.java:33)
	at com.naver.searchad.api.sample.AdManagementSample.main(AdManagementSample.java:32)
```

`GET /ncc/ads` 로 요청하면 아래와 같이 ids가 가능하다고 나옵니다. 
```
{"title":"Bad Request","status":400,"detail":"Parameter conditions \"nccAdgroupId\" OR \"nccLabelId\" OR \"ids\" not met for actual request parameters: "}
java.lang.Exception: 400 Bad Request. X-Transaction-ID: BG1TNFRNH9JJR, Response Body: {"title":"Bad Request","status":400,"detail":"Parameter conditions \"nccAdgroupId\" OR \"nccLabelId\" OR \"ids\" not met for actual request parameters: "}
	at com.naver.searchad.api.util.RestClient.asObject(RestClient.java:143)
	at com.naver.searchad.api.rest.Ads.list(Ads.java:33)
	at com.naver.searchad.api.sample.AdManagementSample.main(AdManagementSample.java:32)
```
혹시 없어진 인터페이스인가요?

확인 부탁드립니다.

**Comment by naver-searchad** [comment]
안녕하세요, 네이버 검색광고 API입니다.

ids로 조회하실 경우는 ad의 id들을 콤마로 구분해서 파라미터 갑에 입력해야 합니다.
올려주신 id는 'grp-'로 시작하는 adgroup의 id입니다.
만약 특정 광고그룹에 들어 있는 ad를 조회하고 싶으신 경우는
`/ncc/ads?nccAdgroupId=grp-a001-01-000000009585414`
처럼 하나의 광고그룹 id를 파라미터로 넣어서 요청하시면 됩니다.
