### ISSUE TITLE
API 통신 호출 시 에러 (#45 내용 추가본)

### ISSUE THREAD

**Issue by ChoiDaeJung** [naver/searchad-apidoc#51]
안녕하세요.
오늘 같은 에러가 또 3번 발생을 하였습니다.
한가지 특이상 점은 같은 CustomerID에서 발생을 했습니다.
필요 하실지 몰라 해당 관련 정보 올려드려요.

###########################################################################
에러 발생시간(대략) : 2017-03-21 04:04:08.443, 2017-03-21 12:04:12.773, 2017-03-21 16:30:40.843
에러 CustomerID : 381133
에러메시지 :
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
###########################################################################

**Comment by naver-searchad** [comment]
해당 정보만 가지고는 확인이 힘드네요.
JDK 버전 및 stack trace도 함께 남겨주시면 감사하겠습니다.

**Comment by ChoiDaeJung** [comment]
###########################################################################
## 개발환경
###########################################################################
Java : jdk1.8.0_111
Tomcat : apache-tomcat-8.0.39

###########################################################################
## 에러 발생전 API 통신 로그
###########################################################################
============ Request =============
GET /ncc/ads?nccAdgroupId=grp-m001-01-000001512284957 HTTP/1.1
accept-encoding: gzip
user-agent: unirest-java/1.3.11
X-API-KEY: 0100000000a8feb933b05a8c1ba8f13f082ec92f3b0e40c58921c2ff37594d8e541c112711
X-Customer: 381133
X-Signature: fd70N2TEWUcfyO5PfpSRdLq+hpqXGSz08FxQPk9rxes=
X-Timestamp: 1490232516184

============ Response ============
HTTP/1.1 200 OK
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: AQV33PHE1PK9B
Content-Type: application/json;charset=UTF-8
Date: Thu, 23 Mar 2017 01:28:34 GMT

[]
============ Request =============
GET /ncc/targets?ownerId=grp-m001-01-000001512285545&types=TIME_WEEKLY_TARGET HTTP/1.1
accept-encoding: gzip
user-agent: unirest-java/1.3.11
X-API-KEY: 0100000000a8feb933b05a8c1ba8f13f082ec92f3b0e40c58921c2ff37594d8e541c112711
X-Customer: 381133
X-Signature: oNjpVYz11QWf3Vvh2yixhWK2cZDR5p5HrYtLUalUXuU=
X-Timestamp: 1490232516216

============ Response ============
HTTP/1.1 200 OK
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: AQV33PHM9PK9C
Content-Type: application/json;charset=UTF-8
Date: Thu, 23 Mar 2017 01:28:34 GMT

[{"nccTargetId":"tgt-m001-01-000001512285545","ownerId":"grp-m001-01-000001512285545","targetTp":"TIME_WEEKLY_TARGET","target":{"FRI":261632,"MON":261632,"TUE":261632,"SAT":0,"THU":261632,"WED":261632,"SUN":0},"delFlag":false,"regTm":"2016-06-22T04:13:17.000Z"}]
============ Request =============
GET /ncc/keywords?nccAdgroupId=grp-m001-01-000001512285545 HTTP/1.1
accept-encoding: gzip
user-agent: unirest-java/1.3.11
X-API-KEY: 0100000000a8feb933b05a8c1ba8f13f082ec92f3b0e40c58921c2ff37594d8e541c112711
X-Customer: 381133
X-Signature: ke/rtRFgOfZ206YvqkVQm3zNtZhRSrpZGgyEgQ5fgT8=
X-Timestamp: 1490232516248

============ Response ============
HTTP/1.1 200 OK
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: AQV33PHUHPK9E
Content-Type: application/json;charset=UTF-8
Date: Thu, 23 Mar 2017 01:28:34 GMT

###########################################################################
## 에러 stack trace
###########################################################################
com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at com.naver.searchad.api.rest.Keywords.list(Keywords.java:29)
	at com.module.autobid.batch.naver.service.impl.BatchServiceImpl.syncAdvertiserInfoWithPerformance(BatchServiceImpl.java:391)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:318)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:50)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:42)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:90)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor$1.call(AsyncExecutionInterceptor.java:80)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
	... 21 more
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:89)
	... 22 more
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:95)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at com.mashape.unirest.http.utils.ResponseUtils.getBytes(ResponseUtils.java:45)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:87)

**Comment by ChoiDaeJung** [comment]
추가로 필요하실까봐 정보 하나더 올려드려요.
해당 프로세스는 광고주별 쓰레드로 동시에 실행을 진행 하고있습니다.

**Comment by naver-searchad** [comment]
@ChoiDaeJung 
답변이 늦어 죄송합니다. 조사를 광범위하게 진행하고 모든 케이스에 대해 검토 했습니다만 
특정 계정 하나에서만 문제가 발생한다는 현상에 대한 명확한 원인 파악은 하지 못한 상황입니다. 
혹 유사한 현상을 보이는 다른 계정은 없는지요?

p.s 이 게시판은 전체 공개이므로 엑세스라이선스나 커스터머 아이디 전문을 노출 하시지 않으시는 
것이 좋겠습니다.

**Comment by ChoiDaeJung** [comment]
현재 130여개 계정중 4~6개 정도가 고정으로 발생하는 계정이 있습니다.
정보는 어떻게 보내드려야 할까요?

**Comment by naver-searchad** [comment]
@ChoiDaeJung 

검색광고센터>온라인 문의하기에 로그인 하시고 들어가 보시면 API 관련 문의가 있습니다.
그쪽에 커스터머 아이디를 알려 주시면 되겠습니다.

**Comment by naver-searchad** [comment]
@ChoiDaeJung 

온라인 문의 주신 사항 접수 되어 담당자에게 전달 되었습니다. 
번거로우실터인데 다시 전달 주신점 감사드립니다.

**Comment by junyoungJeong** [comment]
@naver-searchad 저도 동일한 에러가 발생하고 있는것 같습니다.
/ncc/managedKeyword 를 날릴때 에러가 발생하고 있습니다.

``com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
	at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
	at com.nhnent.searchad.api.rest.ManagedKeywords.listByKeywords(ManagedKeywords.java:27)
	at com.nhnent.searchad.api.process.KeywordEstimateApi.largePcEstimateByPosition(KeywordEstimateApi.java:352)
	at com.nhnent.quartz.bo.common.KeywordEstimateBOImpl.LargeQuantityKeywordCreate(KeywordEstimateBOImpl.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:302)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy69.LargeQuantityKeywordCreate(Unknown Source)
	at com.nhnent.quartz.job.common.LargeQuantityKeywordCreateJob.executeInternal(LargeQuantityKeywordCreateJob.java:67)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
	... 23 more
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:89)
	... 24 more
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.readV3Record(InputRecord.java:596)
	at sun.security.ssl.InputRecord.read(InputRecord.java:532)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
	at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:95)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
	at com.mashape.unirest.http.utils.ResponseUtils.getBytes(ResponseUtils.java:45)
	at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:87)
	... 24 more``
