### ISSUE TITLE
StatReportSample

### ISSUE THREAD

**Issue by Gregcake** [naver/searchad-apidoc#84]
Hi,

I'm trying to run StatReportSample.java. I keep encountering this error:
```
============ Response ============
HTTP/1.1 400 Bad Request
Connection: close
Cache-Control: no-store, must-revalidate
X-Transaction-ID: B13GF0HCHPLQ3
Content-Type: application/json;charset=UTF-8
Date: Mon, 22 Jan 2018 04:26:25 GMT
Strict-Transport-Security: max-age=15768000

{"code":11001,"message":"??? ???? ?????."}
java.lang.Exception: 400 Bad Request. X-Transaction-ID: B13GF0HCHPLQ3, Response Body: {"code":11001,"message":"??? ???? ?????."}
        at com.naver.searchad.api.util.RestClient.asObject(RestClient.java:143)
        at com.naver.searchad.api.rest.StatReports.create(StatReports.java:19)
        at com.naver.searchad.api.sample.StatReportSample.main(StatReportSample.java:27)
```

Is someone able to help me? I'm not sure whats wrong. I updated the sample properties file with my own credentials, and I'm able to pull MasterReportSample.java data with no problem.

Thanks!

**Comment by Gregcake** [comment]
I think the issue I'm encountering is "문의 드립니다", but my console can't display the characters

**Comment by naver-searchad** [comment]
Hi

You received bad_request because you requested an invalid lookup date.
Normal requests are only available for dates after 2016-07-01.

thanks.

**Comment by Gregcake** [comment]
Hi,

I have changed the date to 2016-08-01. Still receiving the same error. Please help!
```
package com.naver.searchad.api.sample;

import com.naver.searchad.api.model.StatReport;
import com.naver.searchad.api.rest.StatReports;
import com.naver.searchad.api.util.PropertiesLoader;
import com.naver.searchad.api.util.RestClient;

import java.util.Properties;

public class StatReportSample {

	public static void main(String[] args) {
		try {

			Properties properties = PropertiesLoader.fromResource("sample.properties");
			String baseUrl = properties.getProperty("BASE_URL");
			String apiKey = properties.getProperty("API_KEY");
			String secretKey = properties.getProperty("SECRET_KEY");
			long customerId = Long.parseLong(properties.getProperty("CUSTOMER_ID"));

			RestClient rest = RestClient.of(baseUrl, apiKey, secretKey);

			String reportType = "AD";
			String statDate = "2016-08-01";

			// 리포트 요청 POST /stat-reports
			StatReport statReport = StatReports.create(rest, customerId, reportType, statDate);
			long reportJobId = statReport.getReportJobId();

			// 리포트 조회 GET /stat-reports/{reportJobId}
			StatReport singleStatReport = StatReports.get(rest, customerId, reportJobId);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
```


Thanks

**Comment by naver-searchad** [comment]
Sorry, You must request it in yyyymmdd format.
