### ISSUE TITLE
javax.net.ssl.SSLException: SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by Gregcake** [naver/searchad-apidoc#91]
I am getting SSL Exception when i try to list all keyword ids for a customer ID.
`com.mashape.unirest.http.exceptions.UnirestException: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:143)
        at com.mashape.unirest.request.BaseRequest.asString(BaseRequest.java:56)
        at com.naver.searchad.api.rest.Keywords.listByAdgroupId(Keywords.java:19)
        at com.naver.searchad.api.sample.main.main(main.java:93)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:106)
        at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:139)
        ... 3 more
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at com.mashape.unirest.http.HttpResponse.<init>(HttpResponse.java:89)
        ... 4 more
Caused by: javax.net.ssl.SSLException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:195)
        at org.apache.http.impl.io.IdentityInputStream.read(IdentityInputStream.java:95)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:137)
        at com.mashape.unirest.http.utils.ResponseUtils.getBytes(ResponseUtils.java:45)
        at com.mashape.`

Please help

**Comment by naver-searchad** [comment]
Hi. 

Sorry for not helping you. I have been involved in related problems in the past, but the reasons are so diverse that it is hard to give a guide. I will not be able to offer a specific solution.

Thanks
